### ISSUE TITLE
get-pvs-patches.in missing

### ISSUE THREAD

**Issue by ptroja** [SRI-CSL/PVS#40]
The `configure` script fails because `get-pvs-patches.in` was not included in commit 281c5ef1ae50e39d5221ea9ce88e4c1476d182be.

**Comment by samowre** [comment]
Hi Piotr,

I just now added it.  Let me know if there are any other issues.
Thanks,

Sam

**Comment by ptroja** [comment]
There is still a small issue in `configure.in`, line 148: `get-pvs-patches` should be changed to `pvs-get-patches`.

**Comment by ptroja** [comment]
This was fixed in 7acc492c.
