### ISSUE TITLE
the binary package is a "tar bomb"

### ISSUE THREAD

**Issue by jwaldmann** [SRI-CSL/PVS#43]
(this is a minor nitpick, but still ...) the file is named `pvs-6.0-ix86_64-Linux-sbclisp.tgz` but it extracts to `bin`, `lib`, etc. cf. http://www.linfo.org/tarbomb.html

**Comment by dddejan** [comment]
I've experienced this several times. It would be great if this can be fixed for future releases.

**Comment by samowre** [comment]
This is fixed in pvs 7.0.  A pre-release is available in http://www.csl.sri.com/~owre/drop/pvs-snapshots
