### ISSUE TITLE
PVS does not compile

### ISSUE THREAD

**Issue by BrunoDutertre** [SRI-CSL/PVS#51]
The latest commit is broken.

Allegro complains with this error:

; Fast loading /Users/bruno/Repos/PVS/src/groundeval/pvs2clean.n64fasl
The lists of keys and data are of unequal length.; Exiting
make: *** [bin/ix86-MacOSX/devel/pvs-allegro] Error 1

**Comment by samowre** [comment]
Sorry, I should have pushed this last night.

**Comment by BrunoDutertre** [comment]
Fixed by ee2091369
