### ISSUE TITLE
PVS fails to close

### ISSUE THREAD

**Issue by ivanperez-keera** [SRI-CSL/PVS#56]
When I try to close PVS 6.0 (the interactive, emacs version) with `C-c C-x`, it asks if I want to close PVS, and if I say yes (`y`), it goes into some sort of endless loop. I can interrupt this with `C-g`, and request it again, but it won't behave differently.

**Comment by samowre** [comment]
Hi Ivan,

Which OS system and version of Emacs are you running?

Thanks,
Sam

**Comment by ivanperez-keera** [comment]
I'm using Emacs 25.2.2, and Ubuntu 18.04 LTS.
