### ISSUE TITLE
Parsing inconstistency - pvs7.0-1057-g6caccf27-ix86_64-Linux-allegro

### ISSUE THREAD

**Issue by clementblaudeau** [SRI-CSL/PVS#67]
I'm trying to write comparison relations, but PVS have an inconsistent behaviour. Here is a minimal reproduction of the problem. The attached code does not type check, but does if you uncomment the center line:
```[language=PVS]
githubIssue : THEORY
BEGIN
    f, g : VAR [nat -> nat]
    <= (f,g) : bool = forall (i:nat) : f(i)<=g(i)
    %uncomment_me_and_it_works : VAR nat % <- line to uncomment
    <  (f,g) : bool = (f <= g) and (Exists (i:nat) : f(i) < g(i))    
END githubIssue
```

**Comment by cesaramh** [comment]
You need to put a semicolon before the definition of an infix operator. Otherwise, the parser cannot solve the ambiguity, e.g.,
;<= (f,g) : bool = forall (i:nat) : f(i)<=g(i)
;<  (f,g) : bool = (f <= g) and (Exists (i:nat) : f(i) < g(i))

**Comment by clementblaudeau** [comment]
Thank you ! I misread the spec
